### ISSUE TITLE
/accessToken & /refreshToken endpoints

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server_nodejs#100]
So that client applications can request new ones so that their local tokens can be refreshed and updated.

**Comment by thehabes** [comment]
are these `/client/request-new-access-token` and `/client/request-new-refresh-token` now?

**Comment by thehabes** [comment]
Connected to #103

**Comment by cubap** [comment]
legacy support for `api/accessToken` and `api/refreshToken`
