### ISSUE TITLE
Toggle "maintenance mode"

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server_nodejs#12]

**Comment by thehabes** [comment]
Dependent on, and will be resolved with, #13

**Comment by thehabes** [comment]
Still need to code in the detection of the `down` flag and resulting redirect to the maintenance message.

**Comment by thehabes** [comment]
I didn't quite punch this through.  This is the pseudo code that immediately popped into my head when I saw this.

There is a special routing method, app.all(), used to load middleware functions at a path for all HTTP request methods. For example, the following handler is executed for requests to the route “/api” whether using GET, POST, PUT, DELETE, or any other HTTP request method supported in the http module.
```javascript 
app.all('/api', (req, res, next) => {
  if(down){
      req.status(503).redirectToSadFace()
  }
  else{
      next() // pass control to the next handler  
  }
})
```

**Comment by cubap** [comment]
This should be a middleware. You can check all requests and redirect or let it go. Then you just app.use(maintenance), for example.

**Comment by thehabes** [comment]
I'll believe it when I see it.  Not sure why using middleware would be more succinct/better than using the following in app.js
```javascript
app.all('/', (req, res, next) => {
  const down = process.env.down
  if(down){
      req.status(503).redirectToSadFace()
  }
  else{
      next() //pass on to the next app.use
  }
})
app.use('/', indexRouter)
app.use('/v1', apiRouter)
```

I haven't played with it yet, and don't know exactly how it would work, so maybe this doesn't make sense.  If it works like this, though, this would seem to be an easy way to go about it.
