### ISSUE TITLE
Access-Control-Allow-Headers is not set

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/rerum_server_nodejs#3]
https://github.com/cubap/TinyNode/issues/6 is waiting for this

Add location.

**Comment by thehabes** [comment]
Location header has been added to the response of `/create` and `/overwrite`.  Relevant CORS headers have been added as well.  This was tested and confirmed, see below.

Added `Location` header and relevant CORS headers to the create/overwrite/query/id routes (brute force added in each route.  I bet there's a better way...)
![image](https://user-images.githubusercontent.com/3287006/135922624-97f1dab9-da8a-4372-8889-ba129160b7cd.png)

overwrite worked.  Confirmed by resolving https://rerum-server-nodejs.herokuapp.com/v1/id/615b652394bf40cf19bcabe5.  However the Heroku TT did that funny thing...
![image](https://user-images.githubusercontent.com/3287006/135922681-557017cc-b085-4275-8028-77ae49f884f7.png)

query found it
![image](https://user-images.githubusercontent.com/3287006/135922782-a23a2a16-536d-44ad-9cb7-9d93ca7749f8.png)
