### ISSUE TITLE
Keep node running indefinitely : v1-node

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server_nodejs#56]
When your connection to the online terminal times out or you ctrl+c out of the logs after typing `npm start`, the server stops listening to itself.  In timeout scenarios and hitting the x to close the window browser, it keeps running as process but is not accessible via the browser.

There should be a way to npm start that allows us to exit the log tail, timeout, and close the browser without affecting application availability via the web.

**Comment by cubap** [comment]
You can run node as a service. It works on the server when it redeploys from new pushes to `main`, unless I am missing something.
