### ISSUE TITLE
req.user[agent]

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server_nodejs#74]
.env says `RERUM_AGENT_CLAIM=rerum_agent`

In /create req.user is `http://devstore.rerum.io/v1/agent': 'http://devstore.rerum.io/v1/id/5b2c0d5de4b0fc5d4aeb709f'`

`let generatorAgent = req.user[process.env.RERUM_AGENT_CLAIM] ?? "http://dev.rerum.io/agent/CANNOTBESTOPPED"`

The generating agent on all the object is `"http://dev.rerum.io/agent/CANNOTBESTOPPED"`

**Comment by cubap** [comment]
Refresh your token. the rule is changed on Auth0. The default claim should be included and the CANNOTBESTOPPED should be an error state.
