### ISSUE TITLE
/release

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server_nodejs#81]

**Comment by thehabes** [comment]
/release/id?slug=bry 
intends to overwrite the `_id`.
-- references to the old object would break, as this overwrites the `_id`. 
put something in __rerum that is a SLUG so you can look it up by _id and SLUG.  both /v1/ids would have to resolve, but this is no big deal for getById
This makes checking for Slug collisions difficult.  Mongo does this automatically with the _id property, but would not do it automatically with the __rerum.slug property (this would have to be coded into lookups).

Make sure Slugs don't conflict with each other or an existing _id

Also support passing in /release/123123?slug= or req.headers["Slug"]

**Comment by cubap** [comment]
#151 changes some of this behavior
