### ISSUE TITLE
Tokens Not Visible During Registration

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server_nodejs#95]
For Java v1 the landing page is the registration page.  Node v1 does not yet have a landing page.  The node v1 registration page is register.html.

**Comment by cubap** [comment]
We can check the links, but I kind of like the simple index.ejs we've got right now

**Comment by thehabes** [comment]
Signing up or signing in to Auth0 redirects you to nowhere if there isn't an index.  Our redirect could go to register.html, but that falls away from the flow of our other apps.  What do?

**Comment by thehabes** [comment]
This is basically just the redirect_uri you pass to the Auth0 widget.  Other apps use `state` now, and perhaps this one should to.  The value of the redirect should be /register.html.

**Comment by thehabes** [comment]
This redirects properly, but we loose the Auth0 parameters like `code` and `access_token` so the page does not do the automatic functionality we want.

**Comment by thehabes** [comment]
Bumping this to a top priority.  OSS students attempting to get tokens are confused, we need to fix this ASAP.

**Comment by thehabes** [comment]
Double bump because @kate-holdener reported this today.  She was trying to sign up with https://devstore.rerum.io/v1/ to get a token and try to communicate with the app.  She hit a dead end because she never saw her token, and so was not able to complete the process.

This is a required step for new contributors and for anyone trying to deploy a sister RERUM.  This really needs to be fixed, think about POSE.
